import React, { useState, useEffect } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
//Packages
import Transition from 'react-transition-group/cjs/Transition';
//Components
import Navigation from '../components/Navigation'
import EligibilityForm from '../components/EligibilityForm'

export default function Home() {

  const [showForm, setShowForm] = useState(false);
 
  const scrollToForm = () => {
    document.getElementById('formContainer').scrollIntoView({
      alignToTop: false,
      behavior: 'smooth'
    })
  }

  const scrollToTop = () => {
    window.scroll({
      top: 0,
      behavior: 'smooth'
    })
  }
 
  useEffect(()=>{
    if(showForm){
      setTimeout(()=>{
        scrollToForm()
      },300)
      } else {
        scrollToTop()
      }
  },[showForm])


  return (
    <div className={styles.container}>
      <Head>
        <title>Orangebox Training | Find a course</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ob.ico" />
      </Head>
      <Navigation />
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Orangebox Training Solutions
        </h1>
        <h2 className={styles.subtitle}>Job Hub</h2>
        <p className={styles.description}>
          Get started by completing our eligibility questionnaire to find out whether you could get a job with us today!
        </p>
        <button className={styles.getStartedBtn} onClick={() => {
          setShowForm(!showForm);
          }}>Get Started</button>
      </main>

      <div id='formContainer' className={styles.formContainer}>
      <Transition in={showForm} timeout={150} mountOnEnter >
        {state => {
          console.log(state);
          return (
            <EligibilityForm show={state}/>
          )
        }}
      </Transition>
      </div>

      <footer className={styles.footer}>
        <p>Powered by</p>
        <a href="https://imraydigital.co.uk">
          <Image src='/images/imray-digital.svg' id="idLogo" height={60} width={60} />
        </a>
      </footer>
    </div>
  )
}
